#!/usr/bin/env node
// Generates fv_fix_now_console.js — ONE console paste that fully repairs the
// Weinstein numbering incident and deploys the numbering fix, end to end:
//   1. Jobs_Master: cancel stale Brad Weinstein *-00057 rows that duplicate a
//      same-client, same-phase *-00059 row (kept as Cancelled, never deleted)
//   2. Active Jobs: recycle stale "…00057 …Weinstein…" folder(s) — only if
//      verifiably empty except the auto-seeded DRAFT contract (recycle bin =
//      recoverable)
//   3. Site Assets master fortivo_app.html: MINT hardening (4 anchored edits)
//      + Job Kickoff block replaced with GUARD V2 — the FIX ONLY; the paused
//      app features (Job Name field, Edit Job) are NOT included
//   4. fortivo_app.aspx republished from the patched master (canary-first,
//      BOM'd, byte-verified) — no separate deployer run needed
// Idempotent and abort-safe: every stage checks state first; any failed
// verification stops before anything is written for that stage.
//   node install/build_fix_now.js   → install/fv_fix_now_console.js
'use strict';
const fs = require('fs');
const path = require('path');
const { MINT_PATCHES, MINT_MARKER } = require('./mint_patches');

const OUT = path.join(__dirname, 'fv_fix_now_console.js');
const kickoff = fs.readFileSync(path.join(__dirname, '..', 'job-kickoff', 'fv_job_kickoff.snippet.html'), 'utf8').trim();
const KICKOFF_TOKEN = 'FORTIVO JOB KICKOFF';
const KICKOFF_MARKER = 'FVK GUARD V2';
if (!kickoff.includes(KICKOFF_MARKER)) throw new Error('kickoff snippet lost GUARD V2 marker');
if (kickoff.split(KICKOFF_TOKEN).length - 1 !== 2) throw new Error('kickoff token must appear exactly twice');
const inner = kickoff.slice(kickoff.indexOf('<script>') + 8, kickoff.lastIndexOf('</' + 'script>'));
if (inner.toLowerCase().includes('</' + 'script')) throw new Error('kickoff JS contains literal closing script tag');

const out = `/* ═══════════════════════════════════════════════════════════════════════════
   FORTIVO FIX-NOW — one paste, complete repair (2026-09-08)
   GENERATED by ops-automation/install/build_fix_now.js — do not hand-edit.
   Run in the browser console on:
     https://fortivopropertyservices.sharepoint.com/sites/FortivoOperations
   Does everything in one run (≈60–90s): cancels stale Weinstein 00057 rows,
   recycles the empty stale 00057 folder, patches the Job Manager master with
   the numbering fix (MINT hardening + Kickoff GUARD V2 — no new app
   features), and republishes fortivo_app.aspx canary-first. Every write is
   verified; failures abort that stage with a clear message. Idempotent.
   ═══════════════════════════════════════════════════════════════════════ */
(async function fvFixNow(){
'use strict';
const OPS = '/sites/FortivoOperations';
const AJOBS = '/sites/ActiveJobs';
const ROOT = '/sites/ActiveJobs/Shared Documents/01_Active Jobs/01_Job Name';
const stamp = new Date().toISOString().slice(0,10).replace(/-/g,'');
const MINT_MARKER = ${JSON.stringify(MINT_MARKER)};
const MINT_PATCHES = ${JSON.stringify(MINT_PATCHES, null, 1)};
const KICKOFF_TOKEN = ${JSON.stringify(KICKOFF_TOKEN)};
const KICKOFF_MARKER = ${JSON.stringify(KICKOFF_MARKER)};
const KICKOFF_SNIPPET = ${JSON.stringify(kickoff)};
const BOM = new Uint8Array([0xEF,0xBB,0xBF]);
const results = [];
const log = (m) => { results.push(m); console.log(m); };
const enc = (s) => encodeURIComponent(String(s).replace(/'/g, "''"));
const digests = {};
async function digest(site){
  const d = digests[site];
  if (d && d.exp > Date.now()) return d.value;
  const r = await fetch(site + '/_api/contextinfo', { method:'POST', headers:{ Accept:'application/json;odata=nometadata' } });
  if (!r.ok) throw new Error('contextinfo ' + r.status + ' on ' + site);
  const v = (await r.json()).FormDigestValue;
  digests[site] = { value:v, exp: Date.now() + 20*60*1000 };
  return v;
}
async function spGetJson(site, api){
  const r = await fetch(site + '/_api/' + api, { headers:{ Accept:'application/json;odata=nometadata' } });
  if (!r.ok) throw new Error('GET ' + api.split('?')[0] + ' ' + r.status);
  return r.json();
}
async function spPost(site, api, opts){
  opts = opts || {};
  const h = Object.assign({ Accept:'application/json;odata=verbose', 'X-RequestDigest': await digest(site) }, opts.headers || {});
  return fetch(site + '/_api/' + api, { method:'POST', headers:h, body: opts.body });
}

/* ── 1. Jobs_Master rows ─────────────────────────────────────────────────── */
try {
  const data = await spGetJson(OPS, "web/lists/getbytitle('Jobs_Master')/items?$select=Id,Job_Number,Title,Client_Name,Job_Status&$top=2000");
  const rows = (data.value || []).map(r => ({
    id: r.Id, num: String(r.Job_Number || r.Title || '').trim(),
    client: String(r.Client_Name || '').trim(), status: r.Job_Status || ''
  }));
  const wein = rows.filter(r => /weinstein/i.test(r.client));
  log('Jobs_Master Weinstein rows: ' + (wein.map(r => r.num + ' [' + (r.status||'?') + ']').join(', ') || 'none'));
  const parse = (n) => { const m = /^(\\d{2})-(\\d{2})-(\\d{5})/.exec(n); return m ? { pp:m[2], seq:m[3] } : null; };
  const listMeta = await spGetJson(OPS, "web/lists/getbytitle('Jobs_Master')?$select=ListItemEntityTypeFullName");
  for (const r of wein) {
    const p = parse(r.num);
    if (!p || p.seq !== '00057') continue;
    if (/cancelled/i.test(r.status)) { log('row ' + r.num + ': already Cancelled'); continue; }
    const twin = wein.find(o => o.id !== r.id && (parse(o.num)||{}).pp === p.pp && (parse(o.num)||{}).seq === '00059');
    if (!twin) { log('row ' + r.num + ': SKIPPED (no 00059 twin — not provably stale)'); continue; }
    const u = await spPost(OPS, "web/lists/getbytitle('Jobs_Master')/items(" + r.id + ')', {
      headers:{ 'Content-Type':'application/json;odata=verbose', 'IF-MATCH':'*', 'X-HTTP-Method':'MERGE' },
      body: JSON.stringify({ __metadata:{ type: listMeta.ListItemEntityTypeFullName }, Job_Status:'Cancelled' })
    });
    if (!u.ok && u.status !== 204) throw new Error('row ' + r.num + ' update ' + u.status);
    log('row ' + r.num + ' (Id ' + r.id + '): set to Cancelled — duplicate of ' + twin.num + ' (data kept)');
  }
} catch(e){ log('ROWS STAGE ERROR: ' + e.message); }

/* ── 2. stale folder(s) ──────────────────────────────────────────────────── */
try {
  const kids = await spGetJson(AJOBS, "web/GetFolderByServerRelativePath(DecodedUrl=@f)/Folders?@f='" + enc(ROOT) + "'&$select=Name,ServerRelativeUrl&$top=500");
  const stale = (kids.value || []).filter(f => /^26-\\d{2}-00057\\b.*weinstein/i.test(f.Name));
  if (!stale.length) log('folders: no stale 00057 Weinstein folders remain');
  for (const f of stale) {
    // verify: only the auto-seeded DRAFT contract may exist anywhere inside
    const bad = [];
    async function walk(rel, depth){
      if (depth > 3) return;
      const fl = await spGetJson(AJOBS, "web/GetFolderByServerRelativePath(DecodedUrl=@f)/Files?@f='" + enc(rel) + "'&$select=Name&$top=500");
      (fl.value || []).forEach(x => { if (!/DRAFT/i.test(x.Name)) bad.push(rel + '/' + x.Name); });
      const sub = await spGetJson(AJOBS, "web/GetFolderByServerRelativePath(DecodedUrl=@f)/Folders?@f='" + enc(rel) + "'&$select=Name,ServerRelativeUrl&$top=500");
      for (const s of sub.value || []) { if (s.Name !== 'Forms') await walk(s.ServerRelativeUrl, depth + 1); }
    }
    await walk(f.ServerRelativeUrl, 0);
    if (bad.length) { log('folder "' + f.Name + '": SKIPPED — contains real files: ' + bad.slice(0,5).join(', ')); continue; }
    const d = await spPost(AJOBS, "web/GetFolderByServerRelativePath(DecodedUrl=@f)/recycle()?@f='" + enc(f.ServerRelativeUrl) + "'");
    if (!d.ok) throw new Error('recycle "' + f.Name + '" ' + d.status);
    log('folder "' + f.Name + '": recycled (recoverable from the site recycle bin)');
  }
} catch(e){ log('FOLDER STAGE ERROR: ' + e.message); }

/* ── 3. master patch (fix only) ──────────────────────────────────────────── */
let patchedBytes = null;
try {
  const mr = await fetch(OPS + '/SiteAssets/fortivo_app.html', { headers:{ Accept:'text/html' } });
  if (!mr.ok) throw new Error('master download ' + mr.status);
  const origBuf = await mr.arrayBuffer();
  const ob = new Uint8Array(origBuf);
  const hadBom = ob.length >= 3 && ob[0] === 0xEF && ob[1] === 0xBB && ob[2] === 0xBF;
  let text = new TextDecoder('utf-8').decode(origBuf);
  let changed = false;
  if (text.includes(MINT_MARKER)) log('master: MINT already applied');
  else {
    for (const p of MINT_PATCHES){
      const n = text.split(p.find).length - 1;
      if (n !== 1) throw new Error('MINT anchor check failed (' + n + 'x) — master differs; NOTHING changed.');
    }
    for (const p of MINT_PATCHES) text = text.replace(p.find, p.repl);
    changed = true; log('master: MINT hardening applied (4 edits)');
  }
  if (text.includes(KICKOFF_MARKER)) log('master: Kickoff GUARD V2 already installed');
  else {
    const i1 = text.indexOf(KICKOFF_TOKEN);
    const i2 = i1 === -1 ? -1 : text.indexOf(KICKOFF_TOKEN, i1 + KICKOFF_TOKEN.length);
    if (i1 === -1 || i2 === -1) throw new Error('kickoff block boundaries not found — NOTHING changed.');
    const begin = text.lastIndexOf('<!--', i1), end = text.indexOf('-->', i2);
    if (begin === -1 || end === -1 || text.indexOf(KICKOFF_TOKEN, end) !== -1) throw new Error('kickoff boundaries not clean — NOTHING changed.');
    text = text.slice(0, begin) + KICKOFF_SNIPPET + text.slice(end + 3);
    if (text.split(KICKOFF_TOKEN).length - 1 !== 2 || !text.includes(KICKOFF_MARKER)) throw new Error('kickoff replace verification failed — NOTHING changed.');
    changed = true; log('master: Kickoff replaced with GUARD V2');
  }
  if (!/<\\/body>\\s*<\\/html>\\s*$/i.test(text.slice(-200))) throw new Error('master no longer ends with </body></html> — NOTHING changed.');
  const body = new TextEncoder().encode(text);
  patchedBytes = hadBom ? new Uint8Array(BOM.length + body.length) : body;
  if (hadBom){ patchedBytes.set(BOM, 0); patchedBytes.set(body, BOM.length); }
  if (changed) {
    const backupName = 'fortivo_app_' + stamp + '_prefixnow.html';
    const b = await spPost(OPS, "web/GetFolderByServerRelativePath(DecodedUrl=@f)/Files/AddUsingPath(DecodedUrl=@n,overwrite=@o)?@f='" +
      enc(OPS + '/SiteAssets/_backups') + "'&@n='" + enc(backupName) + "'&@o=false",
      { headers:{ 'Content-Type':'application/octet-stream' }, body: origBuf });
    if (!b.ok && !/already exists|-2130575257/i.test(await b.text())) throw new Error('backup failed — master NOT touched.');
    const u = await spPost(OPS, "web/GetFolderByServerRelativePath(DecodedUrl=@f)/Files/AddUsingPath(DecodedUrl=@n,overwrite=@o)?@f='" +
      enc(OPS + '/SiteAssets') + "'&@n='fortivo_app.html'&@o=true",
      { headers:{ 'Content-Type':'application/octet-stream' }, body: patchedBytes });
    if (!u.ok) throw new Error('master upload ' + u.status + ' — restore _backups/' + backupName);
    log('master: uploaded (backup: _backups/' + backupName + ')');
  }
} catch(e){ patchedBytes = null; log('MASTER STAGE ERROR: ' + e.message); }

/* ── 4. republish the page (canary-first, BOM, byte-verified) ────────────── */
try {
  if (!patchedBytes) throw new Error('skipped — master stage did not complete');
  const served = await fetch(OPS + '/SitePages/fortivo_app.aspx?nocache=' + Date.now(), { headers:{ Accept:'text/html' } });
  const servedText = served.ok ? new TextDecoder('utf-8').decode(await served.arrayBuffer()) : '';
  if (servedText.includes(KICKOFF_MARKER) && servedText.includes(MINT_MARKER)) { log('page: already up to date'); }
  else {
    // canary byte round-trip (em dash + lightning must survive)
    const canaryBody = new TextEncoder().encode('<!-- fv fix-now canary — ⚡ -->');
    const canaryBuf = new Uint8Array(BOM.length + canaryBody.length);
    canaryBuf.set(BOM, 0); canaryBuf.set(canaryBody, BOM.length);
    const cu = await spPost(OPS, "web/GetFolderByServerRelativePath(DecodedUrl=@f)/Files/AddUsingPath(DecodedUrl=@n,overwrite=@o)?@f='" +
      enc(OPS + '/SitePages') + "'&@n='fv_canary_fixnow.aspx'&@o=true", { headers:{ 'Content-Type':'application/octet-stream' }, body: canaryBuf });
    if (!cu.ok) throw new Error('canary upload ' + cu.status + ' — page NOT republished (master IS updated).');
    const cb = new Uint8Array(await (await fetch(OPS + '/SitePages/fv_canary_fixnow.aspx?nocache=' + Date.now(), { headers:{ Accept:'text/html' } })).arrayBuffer());
    const cok = cb.length === canaryBuf.length && cb.every((v,i) => v === canaryBuf[i]);
    await spPost(OPS, "web/GetFileByServerRelativePath(DecodedUrl=@f)/recycle()?@f='" + enc(OPS + '/SitePages/fv_canary_fixnow.aspx') + "'");
    if (!cok) throw new Error('CANARY byte round-trip FAILED — page NOT republished (master IS updated; retry later).');
    log('page: canary OK');
    // proven flow: backup copy → delete → fresh add → verify
    const pageBackup = 'fortivo_app_backup_' + stamp + '_fixnow.aspx';
    const old = await fetch(OPS + '/SitePages/fortivo_app.aspx?nocache=' + Date.now(), { headers:{ Accept:'text/html' } });
    if (old.ok) {
      const oldBuf = await old.arrayBuffer();
      await spPost(OPS, "web/GetFolderByServerRelativePath(DecodedUrl=@f)/Files/AddUsingPath(DecodedUrl=@n,overwrite=@o)?@f='" +
        enc(OPS + '/SitePages') + "'&@n='" + enc(pageBackup) + "'&@o=false", { headers:{ 'Content-Type':'application/octet-stream' }, body: oldBuf });
      log('page: previous version saved as SitePages/' + pageBackup);
    }
    const del = await spPost(OPS, "web/GetFileByServerRelativePath(DecodedUrl=@f)/recycle()?@f='" + enc(OPS + '/SitePages/fortivo_app.aspx') + "'");
    if (!del.ok) throw new Error('old page recycle ' + del.status + ' — aborting republish; page unchanged.');
    const pu = await spPost(OPS, "web/GetFolderByServerRelativePath(DecodedUrl=@f)/Files/AddUsingPath(DecodedUrl=@n,overwrite=@o)?@f='" +
      enc(OPS + '/SitePages') + "'&@n='fortivo_app.aspx'&@o=false", { headers:{ 'Content-Type':'application/octet-stream' }, body: patchedBytes });
    if (!pu.ok) throw new Error('PAGE UPLOAD FAILED ' + pu.status + ' — RESTORE: rename SitePages/' + pageBackup + ' to fortivo_app.aspx (or restore from recycle bin).');
    const back = new TextDecoder('utf-8').decode(await (await fetch(OPS + '/SitePages/fortivo_app.aspx?nocache=' + Date.now(), { headers:{ Accept:'text/html' } })).arrayBuffer());
    if (!back.includes(KICKOFF_MARKER) || !back.includes(MINT_MARKER) || !back.includes('⚡'))
      throw new Error('page verification FAILED — restore SitePages/' + pageBackup);
    log('page: fortivo_app.aspx republished + verified ✓');
  }
} catch(e){ log('PAGE STAGE ERROR: ' + e.message); }

console.log('\\n════════ FIX-NOW RESULT ════════');
results.forEach(r => console.log(typeof r === 'string' ? r : JSON.stringify(r)));
console.log('Done. Hard-refresh the Job Manager (Ctrl/Cmd+Shift+R).');
})().catch(e => console.error('FIX-NOW ABORTED:', e.message));
`;

fs.writeFileSync(OUT, out);
console.log('generated ' + path.basename(OUT) + ' (' + out.length + ' chars)');
